### PR TITLE
Fuge generate repo

### PR DESCRIPTION
**Pull request by mcdonnelldean**
@mihaidma I just want to find that appVeyor issue so adding this wip PR to let it run. It takes a while, lets look at this tomorrow.

### CODE REVIEW

**Comment by mihaidma** [comment]
@mcdonnelldean there was a generator test failing, not ready for PR yet as I want to update also the docs and add some tests

**Comment by mcdonnelldean** [comment]
@mihaidma Good stuff so :D

**Comment by mihaidma** [comment]
@mcdonnelldean made changes, ready for PR

**Comment by mcdonnelldean** [comment]
This is nice!

**Pull request merged**
