### PR TITLE
Command History/ Auto complete added

### PR DESCRIPTION
**Pull request by matthewoconnor-development**
#9

### CODE REVIEW

**Comment by matthewoconnor-development** [comment]
Just need to remove service folders and will re request

**Comment by mcollina** [comment]
Thanks! It's almost impossible to review them in this way. Would you mind to rebase them out, so we that they are not part of the history?

**Comment by matthewoconnor-development** [comment]
will do :)

**Comment by geek** [comment]
@davidmarkclements vorpal uses inquirer + adds the history support.  Also, if you look at the changes to shell, the defaults and help portion can be simplified into config.

**Pull request closed without merging**
