### PR TITLE
added ability to tail just one process

### PR DESCRIPTION
**Pull request by matt-oc**
extended functionality slightly

### CODE REVIEW

**Comment by matt-oc** [comment]
@AdrianRossouw @pelger Can you review this, just a simple change from a process being required to being optional for tailing. Defaults to all if no process is given.

**Comment by AdrianRossouw** [comment]
lgtm

**Comment by AdrianRossouw** [comment]
@matt-oc thanks =)

**Comment by matt-oc** [comment]
@AdrianRossouw no problem, just was using it the other way and this makes life easier.

**Pull request merged**
