### PR TITLE
Command History/ Auto complete added

### PR DESCRIPTION
**Pull request by matt-oc**
#9

### CODE REVIEW

**Comment by davidmarkclements** [comment]
Hey @matthewoconnor-development  - thanks for the work done here - I'm not sure that replacing a small module with an heavier library and refactoring several portions of code in order to add a feature is the right way to go here. 

Essentially to complete this task all we need is an array of history, catch the up arrow key, and pop from the array. For now I'll close this PR but if you want to reopen/discuss/update etc. it's cool to reopen

**Comment by davidmarkclements** [comment]
reopened - but we have a dual approach to prompts

in generator we're using positive and incite (sync prompt micro libraries) 

in shell we're using inquirer (which I think makes more sense for shell) 

if vorpal adds history I guess that's okay, just for frameworks (which inquirer is imo),
I think we should augment rather than encapsulate (e.g. a module that adds history support to inquirer rather than a module that wraps inquirer with a new name, adding a couple of extra features)

**Comment by pelger** [comment]
Hey @matthewoconnor-development @davidmarkclements can you guys please confirm that this PR doesn't break windows functionality - need to be sure of this before merging. Thanks!

**Comment by matthewoconnor-development** [comment]
Hi David, thanks for the feedback. I used this as a little project to get into node so was a fun learning experience! I originally made it using an array and capturing the arrow keys but was asked to make a vorpal version as inquirer in the form used didn't have the needed functionality. That explains the rather drastic change from my end anyway!

**Comment by matthewoconnor-development** [comment]
@pelger @davidmarkclements Tested on windows and it works just as the current one does. It hasn't broken any compatibility. there is an issue in both with "fsevents" module though, it doesn't exist for windows and so skips it, just a warning though.

**Comment by mcollina** [comment]
The fsevent thing is completely normal and expected. That module is only
for mac.
Il giorno gio 4 feb 2016 alle 12:03 matthewoconnor-development <
notifications@github.com> ha scritto:

**Comment by AdrianRossouw** [comment]
this is related to this issue : #29
i didn't realize there was a PR when I made it..

I agree with the desire to have a more powerful REPL than the existing library provides.

**Comment by AdrianRossouw** [comment]
what's the status of this?

**Comment by AdrianRossouw** [comment]
@matt-oc could you re-roll this PR so I can review this for inclusion in the next release?

**Comment by matt-oc** [comment]
@AdrianRossouw will do

**Comment by matt-oc** [comment]
@AdrianRossouw Should be good to go now

**Comment by AdrianRossouw** [comment]
This works great, thanks @matt-oc.

we now have auto-complete of commands.
This would be great when we add auto-complete for process names!

```
? fuge> st*tab*
start  stop
```

and we also have proper trapping of signals (not ctrl-d yet, but still).

```
? fuge> 
 
(^C again to quit)
? fuge> 
```

closes #29

**Comment by matt-oc** [comment]
@AdrianRossouw Thanks! I got asked to make a few small changes to vorpal which are under review now, the Y/n will be disappearing and it will no longer say exit instance of vorpal in the help menu, it will be more generic. I will update this when the new version is released.

**Comment by matt-oc** [comment]
Ok my vorpal changes are now live so will be included standard with new npm installs, existing downloads need to re install vorpal to get the benefits.

**Pull request merged**
