### PR TITLE
Removed generator functionality

### PR DESCRIPTION
**Pull request by mihaidma**
Removed all generator related functionality, dependencies, unused functions

### CODE REVIEW

**Comment by mcollina** [comment]
👍

**Comment by mcdonnelldean** [comment]
👍 

Luca, if your happy..

**Comment by mihaidma** [comment]
should i merge?

**Comment by mcdonnelldean** [comment]
Yes, I'm happy enough with.

Kindest Regards,

Dean

On 14 Jul 2016, at 13:46, Mihai Dima <notifications@github.com<mailto:notifications@github.com>> wrote:


should i merge?

-

**Pull request merged**
